//
// Created by meiyixuan on 2021-12-20.
//

#ifndef PROJECT_TINY_OBJ_LOADER_HEADER_H
#define PROJECT_TINY_OBJ_LOADER_HEADER_H

#define TINYOBJLOADER_USE_DOUBLE
#define TINYOBJLOADER_IMPLEMENTATION
#define TINYOBJLOADER_USE_MAPBOX_EARCUT

#include "tiny_obj_loader.h"

#endif //PROJECT_TINY_OBJ_LOADER_HEADER_H
